CREATE DATABASE BIBLIOTECAMDO

USE BIBLIOTECAMDO

CREATE TABLE LIBROS
(
	IDLIBRO INT PRIMARY KEY IDENTITY(1,1),
	TITULO NVARCHAR(200) NOT NULL,
	AUTOR NVARCHAR(200) NOT NULL,
	ANIOPUBLICACION DATETIME NOT NULL,
	GENERO NVARCHAR(10) NOT NULL,
	NUMEROPAGINAS INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	DISPONIBILIDAD BIT NOT NULL
)

CREATE TABLE AUTOR (
	IDAUTOR INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	NACIONALIDAD NVARCHAR(200),
	ANIONACIMIENTO INT
)

SELECT * FROM AUTOR

ALTER TABLE LIBROS
ADD IDAUTOR INT

ALTER TABLE LIBROS
ADD CONSTRAINT FK_LIBROS_AUTOR FOREIGN KEY (IDAUTOR) REFERENCES AUTOR(IDAUTOR);

EXEC sp_rename 'LIBROS.ANIOPUBLICACION_INT', 'ANIOPUBLICACION', 'COLUMN';

ALTER TABLE LIBROS
DROP COLUMN AUTOR;
