CREATE DATABASE BIBLIOTECAMDO

USE BIBLIOTECAMDO

CREATE TABLE LIBROS
(
	IDLIBRO INT PRIMARY KEY IDENTITY(1,1),
	TITULO NVARCHAR(200) NOT NULL,
	AUTOR NVARCHAR(200) NOT NULL,
	ANIOPUBLICACION DATETIME NOT NULL,
	GENERO NVARCHAR(10) NOT NULL,
	NUMEROPAGINAS INT NOT NULL,
	PRECIO DECIMAL NOT NULL,
	DISPONIBILIDAD BIT NOT NULL
)

INSERT INTO lIBROS (TITULO, AUTOR, ANIOPUBLICACION, GENERO, NUMEROPAGINAS, PRECIO, DISPONIBILIDAD)
VALUES ('A MI PEDRO','SALOMÉ UREÑA','1982-08-09','FEMENINO',58,550.00,1)

SELECT * FROM LIBROS